// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrodsvgepznxwqbzwnhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhyb2RzdmdlcHpueHdxYnp3bmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjE0NTMsImV4cCI6MjA2MDEzNzQ1M30.8ueEnhv-lQpE5ct7-Hl5Yd8tpniWrO3T6giAgSHbIfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);